### ISSUE TITLE
rake resque:scheduler not starting

### ISSUE THREAD

**Issue by utmishra** [octoai/octo.ai#6]
After running `bundle install`,  `rake resque:scheduler` returns errors. Seems like its not picking redis info from config.yml, which has details like redis host and port name.

```
administrators-MacBook-Pro-52:recurring-jobs utkarsh.mishra$ rake resque:scheduler
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/recurring-jobs/lib/config/config/config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/recurring-jobs/lib/config/config/kong_config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/recurring-jobs/lib/config/config.yml
I, [2016-08-09T19:17:46.953892 #33874]  INFO -- Octo: Octo booting up.
I, [2016-08-09T19:17:46.958199 #33874]  INFO -- Octo: I'm connected now.
I, [2016-08-09T19:17:46.958243 #33874]  INFO -- Octo: Setting callbacks.
rake aborted!
nodename nor servname provided, or not known
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/connection/hiredis.rb:17:in `connect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/connection/hiredis.rb:17:in `connect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:178:in `call_pipelined'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:150:in `block in call_pipeline'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis/client.rb:148:in `call_pipeline'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis.rb:2199:in `block in pipelined'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-3.2.2/lib/redis.rb:2195:in `pipelined'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:414:in `namespaced_block'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:266:in `pipelined'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/resque-scheduler-4.1.0/lib/resque/scheduler/scheduling_extensions.rb:126:in `set_schedule'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.5/lib/octocore/scheduler.rb:31:in `block (2 levels) in schedule_counters'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.5/lib/octocore/scheduler.rb:22:in `each'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.5/lib/octocore/scheduler.rb:22:in `block in schedule_counters'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.5/lib/octocore/scheduler.rb:21:in `each'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.5/lib/octocore/scheduler.rb:21:in `schedule_counters'
/Users/utkarsh.mishra/dev/tools/octo/recurring-jobs/lib/recurring_tasks_scheduler.rb:14:in `setup_schedules'
/Users/utkarsh.mishra/dev/tools/octo/recurring-jobs/lib/tasks.rb:25:in `block (2 levels) in <top (required)>'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => resque:scheduler => resque:setup_schedule
(See full trace by running task with --trace)
```

**Comment by pranny** [comment]
Acknowledging this as a bug. Pushed a patch that allows to specify config directory in environment variable as well. You can pull recurring-jobs and try with `rake resque:scheduler CONFIG_DIR=/path/to/config`.

**Comment by utmishra** [comment]
Yes. Works now
